[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
smartcontract = "5vvuTRh8NL8VbGNRdVW9N3c1tS1Qaat8ytuB6LQGxBAo"

[programs.localnet]
smartcontract = "FJ5vnDd8ev6yHiBfgx376u3dLULodyJzgVFxczSLEVfF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/louisfernando/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
