[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
smartcontract = "B8Tzb2B8y8PMxtFwhF8jyjp5gcQLxMDAekiMNvSrCvAz"

[programs.devnet]
smartcontract = "B8Tzb2B8y8PMxtFwhF8jyjp5gcQLxMDAekiMNvSrCvAz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
