[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
smartcontract = "J2DZcUjM84mvzSm8HCoPFx58JouvJ6bogjRPdaeewghx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/louisfernando/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"